baseURL = "http://dobrabasta.sk/"
languageCode = "sk-SK"
title = "Dobrá Bašta"

DefaultContentLanguage = "en"

[params]
currency = "€"

[languages]
[languages.ba]
weight = 1
languageName="Bratislava"
subtitle = "Poctivá domáca kuchyňa v Bratislave"
jsonMenuUrl="https://basta-47101.firebaseio.com/meals.json?location=ba"
jsonOfferUrl="https://basta-47101.firebaseio.com/offer.json?location=ba"
facebook = "http://www.facebook.com/pages/dobrabasta"
zomato = "https://www.zomato.com/bratislava/dobr%C3%A1-ba%C5%A1ta-petr%C5%BEalka-bratislava-v"
googleplus = "https://www.googleplus.com/basta"
googleAnalytics = "UA-123-45"


[languages.pd]
weight = 2
languageName="Prievidza"
subtitle = "Poctivá domáca kuchyňa v Prievidzi"
jsonMenuUrl="https://basta-47101.firebaseio.com/meals.json?location=pd"
jsonOfferUrl="https://basta-47101.firebaseio.com/offer.json?location=pd"
facebook = "http://www.facebook.com/pages/dobrabasta"
zomato = "https://www.zomato.com/bratislava/dobr%C3%A1-ba%C5%A1ta-prievidza"
googleplus = "https://www.googleplus.com/basta"
googleAnalytics = "UA-987-65"


